version: '3.9'

x-default-logging:
  &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

  # OpenTelemetry Collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.76.1
    container_name: collector
    command: [ "--config=/etc/otel-config.yml" ]
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
    ports:
      - "4317" # OTLP over gRPC receiver
      - "4318:4318" # OTLP over HTTP receiver
      - "9464" # Prometheus exporter
      - "8888" # metrics endpoint
    depends_on:
      - jaeger
    logging: *logging

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    command:
      - "--memory.max-traces"
      - "10000"
      - "--query.base-path"
      - "/jaeger/ui"
      - "--prometheus.server-url"
      - "http://prometheus:9090"
    restart: unless-stopped
    ports:
      - "16686:16686" # Jaeger UI
      - "4317" # OTLP gRPC default port
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
    logging: *logging

  # Loki
  loki:
    image: grafana/loki:2.8.0
    container_name: loki
    ports:
      - "3100:3100"
    logging: *logging

  # Promtail
  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    volumes:
      - ./promtail/promtail.yml:/etc/promtail.yml
      - C:/var/log/logs:/var/log # Mount the host's log directory into the container
    ports:
      - "9080:9080" # HTTP port for Promtail
    depends_on:
      - loki
    logging: *logging