scrape_configs:
  - job_name: 'employee-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'bnb-employee-service'

  - job_name: 'child-employee-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'bnb-child-employee-service'

  - job_name: otel
    honor_labels: true
    static_configs:
      - targets:
          - 'collector:9464'

  - job_name: otel-collector
    static_configs:
      - targets:
          - 'collector:8888'