apiVersion: 1

datasources:
  - name: Prometheus
    uid: bnb-metrics
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: bnb-traces
          name: trace_id