apiVersion: 1

datasources:
  - name: Jaeger
    uid: bnb-traces
    type: jaeger
    url: http://jaeger:16686/jaeger/ui
    editable: true
    isDefault: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'bnb-logs'
        spanStartTimeShift: '1h'
        spanEndTimeShift: '5m'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{exporter="OTLP"} | json | spanid="$${__span.spanId}"'
