apiVersion: 1

datasources:
  - name: Loki
    uid: bnb-logs
    type: loki
    url: http://loki:3100
    editable: true
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: bnb-traces
          matcherRegex: '\"traceid\":\"(\w+)'
          name: TraceID
          # url will be interpreted as query for the datasource
          url: '$${__value.raw}'
